import './css/style.css'
import './css/additional-styles/utility-patterns.css'
import './css/additional-styles/toggle-switch.css'
import './css/additional-styles/theme.css'
import './css/additional-styles/range-slider.css'
import { Inter, Architects_Daughter } from 'next/font/google'

import Header from '@/src/app/components/nasus-agro/ui/header'
import Banner from '@/src/app/components/nasus-agro/banner'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})

export const metadata = {
  title: 'Nasus Agro Allied Services Limited',
  description: 'Generated by create next app',
  icons:{
    icon:'/assets/nasus-agro/favicon.ico'
  },
}

export default function NasusAgroLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        
        <title>Nasus Agro - Connecting Smallholder Farmers to Markets</title>
        <meta content="Nasus Agro Allied Limited helps smallholder farmers in Nigeria access global markets by trading high-quality agricultural commodities through sustainable and fair trade practices." name="description" />
        <meta content="smallholder farmers, agricultural commodity trading, exporting Nigerian produce, market access for farmers, sustainable farming Nigeria, fair trade agriculture, Nigerian agricultural products, farm-to-market solutions, agricultural value chain, small-scale farming support, agro-export company Nigeria, connecting farmers to buyers, agricultural supply chain, sustainable farming solutions for smallholder farmers, fair trade opportunities for small-scale farmers" name="Smallholder farmers" />
        <meta name="author" content="Nasus Agro Allied Limited" />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="Nasus Agro Allied Limited - Connecting Smallholder Farmers to Markets" />
        <meta property="og:description" content="Helping smallholder farmers in Nigeria access global markets by trading high-quality agricultural commodities." />
        <meta property="og:image" content="https://nasusagro.vercel.app/assets/nasus-agro/images/logo.png" />
        <meta property="og:url" content="https://www.tacommodity.com/nasus-agro" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Nasus Agro Allied Limited" />
        <meta name="twitter:description" content="Connecting smallholder farmers with buyers in global markets for fair trade and sustainable growth." />
        <meta name="twitter:image" content="https://nasusagro.vercel.app/assets/nasus-agro/images/logo.png" />
        <link href="/favicon.ico" rel="icon" />
        {/* <link href="https://nasusagro.vercel.app/assets/img/ta_logo.png" rel="apple-touch-icon" /> */}

      </head>
      <body className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased bg-gray-900 text-gray-200 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden">
          <Header />
          {children}
          <Banner />
        </div>
      </body>
    </html>
  )
}
 