import { Geist, Geist_Mono, Raleway, Open_Sans, Architects_Daughter, Inter } from "next/font/google";
import "./tacommodity/globals.css";
// import "./styles/styles.css"
// import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const opensans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})

export const metadata = {
  title: "TA Commodity Producers Co Nig Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        
        <title>TA Commodity Producers Co Nig Ltd - Connecting Smallholder Farmers to Markets</title>
        <meta content="TA Commodity Producers Co Nig Ltd helps smallholder farmers in Nigeria access global markets by trading high-quality agricultural commodities through sustainable and fair trade practices." name="description" />
        <meta content="smallholder farmers, agricultural commodity trading, exporting Nigerian produce, market access for farmers, sustainable farming Nigeria, fair trade agriculture, Nigerian agricultural products, farm-to-market solutions, agricultural value chain, small-scale farming support, agro-export company Nigeria, connecting farmers to buyers, agricultural supply chain, sustainable farming solutions for smallholder farmers, fair trade opportunities for small-scale farmers" name="Smallholder farmers" />
        <meta name="author" content="TA Commodity Producers Co Nig Ltd" />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="TA Commodity Producers Co Nig Ltd - Connecting Smallholder Farmers to Markets" />
        <meta property="og:description" content="Helping smallholder farmers in Nigeria access global markets by trading high-quality agricultural commodities." />
        <meta property="og:image" content="https://tacommodity-nextjs.vercel.app/assets/img/ta_commodity_logo.png" />
        <meta property="og:url" content="https://tacommodity-nextjs.vercel.app" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="TA Commodity Producers Co Nig Ltd" />
        <meta name="twitter:description" content="Connecting smallholder farmers with buyers in global markets for fair trade and sustainable growth." />
        <meta name="twitter:image" content="https://tacommodity-nextjs.vercel.app/assets/img/ta_commodity_logo.png" />
        <link href="https://tacommodity-nextjs.vercel.app/assets/img/ta_commodity_logo.png" rel="icon" />
        <link href="https://tacommodity-nextjs.vercel.app/assets/img/ta_logo.png" rel="apple-touch-icon" />


      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${opensans.variable} ${architects_daughter.variable} ${inter.variable} font-inter antialiased bg-gray-900 text-gray-200 tracking-tight`}>
        {children}
      </body>
          
    </html>
  );
}
