import { Geist, Geist_Mono, Raleway, Open_Sans } from "next/font/google";
import "./globals.css";
// import "./styles/styles.css"
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const opensans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});
export const metadata = {
  title: "TA Commodity Producers Co Nig Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta charSet="utf-8" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        {/* {% if page == 'Women_Sustainable_Group' %}
  <title>Port Harcourt Agro Commodity Cooperative Ltd</title>
  {% else %} */}
        <title>TA Commodity Producers Co Nig Ltd - Index</title>
        {/* {% endif %} */}
        <meta content="" name="description" />
        <meta content="" name="keywords" />
        <link href="assets/img/ta_commodity_logo.png" rel="icon" />
        <link href="assets/img/ta_logo.png" rel="apple-touch-icon" />


      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${opensans.variable}`}>
        {children}
      </body>

    </html>
  );
}
